name: Build Assets

on: [pull_request]

jobs:
  build:
    name: Build Assets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Get Bun Cache Directory
        id: bun-cache-dir
        run: echo dir=$(bun pm cache) >> $GITHUB_OUTPUT

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          key: bun-cache-${{ hashFiles('**/bun.lockb') }}
          path: ${{ steps.bun-cache-dir.outputs.dir }}
          restore-keys: bun-cache-

      - name: Install Dependencies
        run: bun install --silent

      - name: Build Assets
        run: bun run build
